### ISSUE TITLE
About DenseASPP

### ISSUE THREAD

**Issue by SuperWWF** [donnyyou/torchcv#42]
Hi, I want try to train denseaspp_model on your code. Can I just change the .sh? Or, could you have
the  script about denseaspp on cityscapes? Thank you.

**Comment by donnyyou** [comment]
Please wait!!! I will add the script for DenseASPP in few days if I have time. Maybe you could try PSPNet and DeepLabv3 which are better than DenseASPP.

**Comment by donnyyou** [comment]
The DenseASPP model in this repo may have some bugs. And I will check it soon. You could refer the https://github.com/donnyyou/torchcv-seg/pull/8

**Comment by donnyyou** [comment]
I have updated the denseaspp scripts without testing. You could check it. I will test it through soon.

**Comment by SuperWWF** [comment]
> I have updated the denseaspp scripts without testing. You could check it. I will test it through soon.

Thank you so much. I am also doing thsi.

**Comment by stigma0617** [comment]
@zhiyuli3 @donnyyou Did you succeed in training denseASPP? I have tried to train denseASPP and failed to start training due to many errors.

There are some bugs in [denseaspp.py](https://github.com/donnyyou/torchcv/blob/master/models/seg/nets/denseassp.py#L40)
[denseaspp.py](https://github.com/donnyyou/torchcv/blob/master/models/seg/nets/denseassp.py#L109)

I managed to solve these bugs, but another problem occurred.

> Traceback (most recent call last):
  File "main.py", line 199, in <module>
    Controller.train(runner)
  File "/home/lsrock1/torchcv/methods/tools/controller.py", line 40, in train
    runner.train()
  File "/home/lsrock1/torchcv/methods/seg/fcn_segmentor.py", line 92, in train
    loss = self.pixel_loss(outputs, targets, gathered=self.configer.get('network', 'gathered'))
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/torchcv/extensions/tools/parallel/data_parallel.py", line 127, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/home/lsrock1/torchcv/extensions/tools/parallel/data_parallel.py", line 188, in _criterion_parallel_apply
    raise output
  File "/home/lsrock1/torchcv/extensions/tools/parallel/data_parallel.py", line 163, in _worker
    output = module(input, *target, **kwargs)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/torchcv/models/seg/loss/seg_modules.py", line 137, in forward
    aux_out, seg_out = inputs
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by donnyyou** [comment]
/home/lsrock1/torchcv/models/seg/loss/seg_modules.py. You could remove aux_out to fix it. And I will update it today.
